steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/faa-gcp-training-14-kfa-0808/sales-predictor', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/faa-gcp-training-14-kfa-0808/sales-predictor']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'sales-predictor',
        '--image',
        'gcr.io/faa-gcp-training-14-kfa-0808/sales-predictor',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - gcr.io/faa-gcp-training-14-kfa-0808/sales-predictor